### ISSUE TITLE
Command-T breaks in jruby projects when compiled for ruby

### ISSUE THREAD

**Issue by stepchud** [wincent/command-t#76]
I've been struggling with this for a while so I thought I'd post it here in case I can get any help. I'm using rvm on osx mavericks. I've installed ruby 1.9.3-p545 (latest) and built vim against it. Then I followed the vimball installation instructions (so %, ruby extconf.rb, make). This works fine using vim with ruby 1.9.3. However if I change to a project directory that is on jruby, I get an error on vim startup:
$ vim config/routes.rb 
Error detected while processing /Users/stephen/dotfiles/vim/plugin/command-t.vim:
line  194:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
Press ENTER or type command to continue

I can press 'enter' to get past the error message and the file loads but command-t does not work. It gives the error message:
Error detected while processing function <SNR>10_CommandTShowFileFinder:
line    2:
NoMethodError: undefined method `show_file_finder' for nil:NilClass

If I open vim from a non-jruby dir then cd to the jruby dir (:cd inside vim), command-t works fine, and updates the file system tree to the current dir.
I've seen the installation instructions about matching vim, ruby, and command-t ruby libs. However, I was able to accomplish this switching ruby versions fine on a previous machine. I'm not sure what is different at this point. Do I need to somehow install different versions of command-t for each version of Ruby I want or is that possible? Help, I'd really like to have command-t back and working across my system. Let me know if I can provide any further details.
